#include <cstdio>
#include <cstring>

#include <sced_types.h>
#include <config.h>

#include "layers.h"

char layerDescription[CED_MAX_LAYER][CED_MAX_LAYER_CHAR];
const char layer_keys[] = { DATALAYER_SHORTKEY_00, DATALAYER_SHORTKEY_01, DATALAYER_SHORTKEY_02, DATALAYER_SHORTKEY_03, DATALAYER_SHORTKEY_04, DATALAYER_SHORTKEY_05, DATALAYER_SHORTKEY_06, DATALAYER_SHORTKEY_07, DATALAYER_SHORTKEY_08, DATALAYER_SHORTKEY_09, DATALAYER_SHORTKEY_10, DATALAYER_SHORTKEY_11, DATALAYER_SHORTKEY_12, DATALAYER_SHORTKEY_13, DATALAYER_SHORTKEY_14, DATALAYER_SHORTKEY_15, DATALAYER_SHORTKEY_16, DATALAYER_SHORTKEY_17, DATALAYER_SHORTKEY_18, DATALAYER_SHORTKEY_19, DATALAYER_SHORTKEY_20, DATALAYER_SHORTKEY_21, DATALAYER_SHORTKEY_22, DATALAYER_SHORTKEY_23, DATALAYER_SHORTKEY_24};

const char detec_layer_keys[] = {
    DETECTORLAYER_SHORTKEY_00, DETECTORLAYER_SHORTKEY_01,
    DETECTORLAYER_SHORTKEY_02, DETECTORLAYER_SHORTKEY_03,
    DETECTORLAYER_SHORTKEY_04, DETECTORLAYER_SHORTKEY_05,
    DETECTORLAYER_SHORTKEY_06, DETECTORLAYER_SHORTKEY_07,
    DETECTORLAYER_SHORTKEY_08, DETECTORLAYER_SHORTKEY_09,
    DETECTORLAYER_SHORTKEY_10, DETECTORLAYER_SHORTKEY_11,
    DETECTORLAYER_SHORTKEY_12, DETECTORLAYER_SHORTKEY_13,
    DETECTORLAYER_SHORTKEY_14, DETECTORLAYER_SHORTKEY_15,
    DETECTORLAYER_SHORTKEY_16, DETECTORLAYER_SHORTKEY_17,
    DETECTORLAYER_SHORTKEY_18, DETECTORLAYER_SHORTKEY_19,
    DETECTORLAYER_SHORTKEY_20, DETECTORLAYER_SHORTKEY_21,
    DETECTORLAYER_SHORTKEY_22, DETECTORLAYER_SHORTKEY_23,
    DETECTORLAYER_SHORTKEY_24, DETECTORLAYER_SHORTKEY_25,
    DETECTORLAYER_SHORTKEY_26, DETECTORLAYER_SHORTKEY_27,
    DETECTORLAYER_SHORTKEY_28, DETECTORLAYER_SHORTKEY_29,
    DETECTORLAYER_SHORTKEY_30, DETECTORLAYER_SHORTKEY_31,
    DETECTORLAYER_SHORTKEY_32, DETECTORLAYER_SHORTKEY_33,
    DETECTORLAYER_SHORTKEY_34, DETECTORLAYER_SHORTKEY_35,
    DETECTORLAYER_SHORTKEY_36, DETECTORLAYER_SHORTKEY_37,
    DETECTORLAYER_SHORTKEY_38, DETECTORLAYER_SHORTKEY_39,
};

void addLayerDescriptionToMenu(int id, char * str){
    if(id < 0 || id >= CED_MAX_LAYER){
        printf("Warning: Layer id out of range\n");
        return;
    }
    strncpy(layerDescription[id], str,CED_MAX_LAYER_CHAR-1);
}

void print_layer_text(CED_TEXT *obj){
    addLayerDescriptionToMenu(obj->id, obj->text);
}
